namespace SpriteKind {
    export const Rock = SpriteKind.create()
    export const Collider = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Collider, SpriteKind.Rock, function (sprite, otherSprite) {
    if (controller.A.isPressed()) {
        sprites.changeDataNumberBy(otherSprite, "Hits", -1)
    }
    if (sprites.readDataNumber(otherSprite, "Hits") < 0) {
        otherSprite.destroy(effects.disintegrate, 500)
    }
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Fox,
    [img`
        .ffbbbbff................
        .fdbbbbdf................
        .bbbbbbbb................
        .b18bb81b................
        .b1fbbf1b................
        .bbbbbbbb................
        .bb1ff1bb................
        .bb1111bb................
        .ccddddccb...............
        .cc11ddccbb..............
        .bb11ddbbbbb.............
        .cb11ddbbbcbb............
        .cb11ddbbbcbb............
        .cb11ddbbccbb............
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        `],
    500,
    false
    )
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Fox,
    [img`
        .........................
        ...ffbbbbff..............
        ...fdbbbbdf..............
        ...bbbbbbbb..............
        ...b18bb81b..............
        ...b1fbbf1b..............
        ...bbbbbbbb..............
        ...bb1ff1bb..............
        ...bb1111bb..............
        ...ccddddccbbb...........
        ...cc11ddccbbbb..........
        ...bb11bbd11dbb..........
        ...cb.1cb11d1bb..........
        ...cb..cb..ccbb..........
        ...cb..bb..ccbb..........
        .........................
        .........................
        .........................
        .........................
        .........................
        `],
    500,
    false
    )
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Fox,
    [img`
        .........................
        ..............ffbbbbff...
        ..............fdbbbbdf...
        ..............bbbbbbbb...
        ..............b18bb81b...
        ..............b1fbbf1b...
        ..............bbbbbbbb...
        ..............bb1ff1bb...
        ..............bb1111bb...
        ...........bbbccddddcc...
        ..........bbbbccdd11cc...
        ..........bbd11dbb11bb...
        ..........bb1d11bc1.bc...
        ..........bbcc..bc..bc...
        ..........bbcc..bb..bc...
        .........................
        .........................
        .........................
        .........................
        .........................
        `],
    500,
    false
    )
})
function Spawn_Rocks () {
    for (let value of tiles.getTilesByType(assets.tile`myTile`)) {
        if (Math.percentChance(70)) {
            Rock = sprites.create(img`
                . f f f f f f f f f f f f . . . 
                f f b b b b b c c c c c f f . . 
                f b b b b b b b c c c c c f f . 
                f b b b b b b b c c c c c c f f 
                f b b b b b b b b c c c c c c f 
                f b b b b b b b b c c c c c c f 
                f b b b b b b b b c c c c c c f 
                f b b b b b b b b c c c c c c f 
                f b b b b b b b c c c c c c c f 
                f f b b b b b c c c c c c c f f 
                . f f b b b b c c c c c c f f . 
                . . f f f f f f f f f f f f . . 
                `, SpriteKind.Rock)
            tiles.placeOnTile(Rock, value)
            tiles.setWallAt(value, true)
            sprites.setDataNumber(Rock, "Hits", 3)
        }
    }
}
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Fox,
    [img`
        .ffbbbbff................
        .fdbbbbdf................
        .bbbbbbbb................
        .b18bb81b................
        .b1fbbf1b................
        .bbbbbbbb................
        .bb1ff1bb................
        .bb1111bb................
        .ccddddccb...............
        .cc11ddccbb..............
        .bb11ddbbbbb.............
        .cb11ddbbbcbb............
        .cb11ddbbbcbb............
        .cb11ddbbccbb............
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        `],
    500,
    false
    )
})
let Rock: Sprite = null
let Fox: Sprite = null
let Hit_Box = sprites.create(img`
    3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
    3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
    3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
    3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
    3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
    3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
    3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
    3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
    3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
    3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
    3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
    3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
    3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
    3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
    3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
    3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
    `, SpriteKind.Collider)
Fox = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . f f b b b b f f . . . . . 
    . . . f d b b b b d f . . . . . 
    . . . b b b b b b b b . . . . . 
    . . . b 1 8 b b 8 1 b . . . . . 
    . . . b 1 f b b f 1 b . . . . . 
    . . . b b b b b b b b . . . . . 
    . . . b b 1 f f 1 b b . . . . . 
    . . . b b 1 1 1 1 b b . . . . . 
    . . . c c d d d d c c b . . . . 
    . . . c c 1 1 d d c c b b . . . 
    . . . b b 1 1 d d b b b b b . . 
    . . . c b 1 1 d d b b b c b b . 
    . . . c b 1 1 d d b b b c b b . 
    . . . c b 1 1 d d b b c c b b . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(Fox)
tiles.setTilemap(tilemap`level1`)
scene.cameraFollowSprite(Fox)
Spawn_Rocks()
let Directions = 1
/**
 * 0 - Up
 * 
 * 1 - Right
 * 
 * 2 - Down
 * 
 * 3 - left
 */
game.onUpdate(function () {
    if (Directions == 0) {
        Hit_Box.setPosition(Fox.x, Fox.y - 16)
    } else if (Directions == 1) {
        Hit_Box.setPosition(Fox.x + 16, Fox.y)
    } else if (Directions == 2) {
        Hit_Box.setPosition(Fox.x, Fox.y)
    } else {
        Hit_Box.setPosition(Fox.x - 16, 0)
    }
})
